// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.0
// source: infa/grpc/cleanservice/ref_sys_agama.proto

package cleanservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infa_grpc_cleanservice_ref_sys_agama_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_infa_grpc_cleanservice_ref_sys_agama_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_infa_grpc_cleanservice_ref_sys_agama_proto_rawDescGZIP(), []int{0}
}

type RefSysAgamas struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string         `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Data    []*RefSysAgama `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (x *RefSysAgamas) Reset() {
	*x = RefSysAgamas{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infa_grpc_cleanservice_ref_sys_agama_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefSysAgamas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefSysAgamas) ProtoMessage() {}

func (x *RefSysAgamas) ProtoReflect() protoreflect.Message {
	mi := &file_infa_grpc_cleanservice_ref_sys_agama_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefSysAgamas.ProtoReflect.Descriptor instead.
func (*RefSysAgamas) Descriptor() ([]byte, []int) {
	return file_infa_grpc_cleanservice_ref_sys_agama_proto_rawDescGZIP(), []int{1}
}

func (x *RefSysAgamas) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RefSysAgamas) GetData() []*RefSysAgama {
	if x != nil {
		return x.Data
	}
	return nil
}

type RefSysAgama struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Nomor      string `protobuf:"bytes,2,opt,name=Nomor,proto3" json:"Nomor,omitempty"`
	Kode       string `protobuf:"bytes,3,opt,name=Kode,proto3" json:"Kode,omitempty"`
	Keterangan string `protobuf:"bytes,4,opt,name=Keterangan,proto3" json:"Keterangan,omitempty"`
}

func (x *RefSysAgama) Reset() {
	*x = RefSysAgama{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infa_grpc_cleanservice_ref_sys_agama_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefSysAgama) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefSysAgama) ProtoMessage() {}

func (x *RefSysAgama) ProtoReflect() protoreflect.Message {
	mi := &file_infa_grpc_cleanservice_ref_sys_agama_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefSysAgama.ProtoReflect.Descriptor instead.
func (*RefSysAgama) Descriptor() ([]byte, []int) {
	return file_infa_grpc_cleanservice_ref_sys_agama_proto_rawDescGZIP(), []int{2}
}

func (x *RefSysAgama) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RefSysAgama) GetNomor() string {
	if x != nil {
		return x.Nomor
	}
	return ""
}

func (x *RefSysAgama) GetKode() string {
	if x != nil {
		return x.Kode
	}
	return ""
}

func (x *RefSysAgama) GetKeterangan() string {
	if x != nil {
		return x.Keterangan
	}
	return ""
}

var File_infa_grpc_cleanservice_ref_sys_agama_proto protoreflect.FileDescriptor

var file_infa_grpc_cleanservice_ref_sys_agama_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x69, 0x6e, 0x66, 0x61, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x6c, 0x65, 0x61,
	0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x72, 0x65, 0x66, 0x5f, 0x73, 0x79, 0x73,
	0x5f, 0x61, 0x67, 0x61, 0x6d, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x72, 0x65,
	0x66, 0x5f, 0x73, 0x79, 0x73, 0x5f, 0x61, 0x67, 0x61, 0x6d, 0x61, 0x22, 0x07, 0x0a, 0x05, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x58, 0x0a, 0x0c, 0x52, 0x65, 0x66, 0x53, 0x79, 0x73, 0x41, 0x67,
	0x61, 0x6d, 0x61, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2e,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72,
	0x65, 0x66, 0x5f, 0x73, 0x79, 0x73, 0x5f, 0x61, 0x67, 0x61, 0x6d, 0x61, 0x2e, 0x52, 0x65, 0x66,
	0x53, 0x79, 0x73, 0x41, 0x67, 0x61, 0x6d, 0x61, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x67,
	0x0a, 0x0b, 0x52, 0x65, 0x66, 0x53, 0x79, 0x73, 0x41, 0x67, 0x61, 0x6d, 0x61, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x4e, 0x6f, 0x6d, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4e, 0x6f,
	0x6d, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x4b, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x4b, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x4b, 0x65, 0x74, 0x65, 0x72,
	0x61, 0x6e, 0x67, 0x61, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4b, 0x65, 0x74,
	0x65, 0x72, 0x61, 0x6e, 0x67, 0x61, 0x6e, 0x32, 0x51, 0x0a, 0x11, 0x52, 0x65, 0x66, 0x53, 0x79,
	0x73, 0x41, 0x67, 0x61, 0x6d, 0x61, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x3c, 0x0a, 0x07,
	0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x2e, 0x72, 0x65, 0x66, 0x5f, 0x73, 0x79,
	0x73, 0x5f, 0x61, 0x67, 0x61, 0x6d, 0x61, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1b, 0x2e,
	0x72, 0x65, 0x66, 0x5f, 0x73, 0x79, 0x73, 0x5f, 0x61, 0x67, 0x61, 0x6d, 0x61, 0x2e, 0x52, 0x65,
	0x66, 0x53, 0x79, 0x73, 0x41, 0x67, 0x61, 0x6d, 0x61, 0x73, 0x42, 0x1a, 0x5a, 0x18, 0x2f, 0x69,
	0x6e, 0x66, 0x61, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_infa_grpc_cleanservice_ref_sys_agama_proto_rawDescOnce sync.Once
	file_infa_grpc_cleanservice_ref_sys_agama_proto_rawDescData = file_infa_grpc_cleanservice_ref_sys_agama_proto_rawDesc
)

func file_infa_grpc_cleanservice_ref_sys_agama_proto_rawDescGZIP() []byte {
	file_infa_grpc_cleanservice_ref_sys_agama_proto_rawDescOnce.Do(func() {
		file_infa_grpc_cleanservice_ref_sys_agama_proto_rawDescData = protoimpl.X.CompressGZIP(file_infa_grpc_cleanservice_ref_sys_agama_proto_rawDescData)
	})
	return file_infa_grpc_cleanservice_ref_sys_agama_proto_rawDescData
}

var file_infa_grpc_cleanservice_ref_sys_agama_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_infa_grpc_cleanservice_ref_sys_agama_proto_goTypes = []interface{}{
	(*Empty)(nil),        // 0: ref_sys_agama.Empty
	(*RefSysAgamas)(nil), // 1: ref_sys_agama.RefSysAgamas
	(*RefSysAgama)(nil),  // 2: ref_sys_agama.RefSysAgama
}
var file_infa_grpc_cleanservice_ref_sys_agama_proto_depIdxs = []int32{
	2, // 0: ref_sys_agama.RefSysAgamas.Data:type_name -> ref_sys_agama.RefSysAgama
	0, // 1: ref_sys_agama.RefSysAgamaServer.GetData:input_type -> ref_sys_agama.Empty
	1, // 2: ref_sys_agama.RefSysAgamaServer.GetData:output_type -> ref_sys_agama.RefSysAgamas
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_infa_grpc_cleanservice_ref_sys_agama_proto_init() }
func file_infa_grpc_cleanservice_ref_sys_agama_proto_init() {
	if File_infa_grpc_cleanservice_ref_sys_agama_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_infa_grpc_cleanservice_ref_sys_agama_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infa_grpc_cleanservice_ref_sys_agama_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefSysAgamas); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infa_grpc_cleanservice_ref_sys_agama_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefSysAgama); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_infa_grpc_cleanservice_ref_sys_agama_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_infa_grpc_cleanservice_ref_sys_agama_proto_goTypes,
		DependencyIndexes: file_infa_grpc_cleanservice_ref_sys_agama_proto_depIdxs,
		MessageInfos:      file_infa_grpc_cleanservice_ref_sys_agama_proto_msgTypes,
	}.Build()
	File_infa_grpc_cleanservice_ref_sys_agama_proto = out.File
	file_infa_grpc_cleanservice_ref_sys_agama_proto_rawDesc = nil
	file_infa_grpc_cleanservice_ref_sys_agama_proto_goTypes = nil
	file_infa_grpc_cleanservice_ref_sys_agama_proto_depIdxs = nil
}
